package com.proj.util;

public enum ObjectType {


	BUTTON,
	BROWSE,
	IMAGE,
	TAB,
	TITLE,
	DATE,
	DROPDOWN_JQX,		
	DROPDOWN_OPTION,
	DROPDOWN_VALUE,
	DROPDOWN,		
	WEBSELECT,
	WEBSELECT_VALUE,
	CHECKBOX,
	CHECKBOX_JQX,
	CHECKBOX_READONLY,				
	MOVETOELEMENT,
	LINK,
	RADIOBUTTON,
	RADIOGROUP,
	RADIOGROUP_JQX,
	TEXTBOX,
	TEXTBOX_GETTEXT,
	TEXTBOX_GETVALUE,
	TEXTBOX_AUTOSUGGEST,
	TEXTBOX_AUTOSUGGEST_SELECT,
	TEXTBOX_AUTOSUGGEST_CHOICE,
	TEXTBOX_AUTOSUGGEST_BROWSE,
	TEXTBOX_DECIMALS,
	TEXTBOX_APPDECIMALS_DBNODECIMALS,//Two Decimals in the application displayed element but the same element value is stored without decimals in DB
	TEXTBOX_APPDECIMALS_DBSINGLEDECIMAL,//Two Decimals in the application displayed element but the same element value is stored with single decimal in DB
	TEXTBOX_MONEY,		
	WEBELEMENT,
	SWITCHTOFRAMEFROMDEFAULT,
	SWITCHTOSINGLEFRAME,
	SELECTITEMBYTEXTFROMLIST,
	ELEMENT_ENABLE,
	ELEMENT_DISABLE,
	ELEMENT_DISABLE_ATTRIBUTE,
	BUTTON_SCROLLABLE



}
